download_supercluster_spec_scores <- function(dest_dir) {
  #' Download Siletti 2024 Supercluster Specificity Scores
  #' 
  #' This function downloads the supercluster specificity scores from Siletti 2024, 
  #' generated by Yao et al. 2025, as published in Nature Communications.
  #' 
  #' Paper link: https://www.nature.com/articles/s41467-024-55611-1#Sec50
  #' 
  #' The function:
  #' - Checks if the `dest_dir` directory exists, creating it if needed.
  #' - Validates the download URL.
  #' - Downloads and extracts the data only if it hasn't been already.
  #' 
  #' Data source:
  #' https://static-content.springer.com/esm/art%3A10.1038%2Fs41467-024-55611-1/MediaObjects/41467_2024_55611_MOESM4_ESM.zip
  
  library(httr)
  library(utils)
  
  url <- "https://static-content.springer.com/esm/art%3A10.1038%2Fs41467-024-55611-1/MediaObjects/41467_2024_55611_MOESM4_ESM.zip"
  
  zip_file <- file.path(dest_dir, "supercluster_spec_scores.zip")
  extracted_folder <- file.path(dest_dir, "Source_Data_v241210")
  
  # Create resources directory if it doesn't exist
  if (!dir.exists(dest_dir)) {
    dir.create(dest_dir, recursive = TRUE)
  }
  
  # Check if URL is accessible
  response <- HEAD(url)
  if (http_error(response)) {
    stop("Error: Unable to access the download link. Please check the URL.")
  }
  
  # Download ZIP file if not already present
  if (!file.exists(zip_file)) {
    message("Downloading supercluster specificity scores...")
    download.file(url, zip_file, mode = "wb")
  } else {
    message("ZIP file already exists. Skipping download.")
  }
  
  # Extract files if not already extracted
  if (!dir.exists(extracted_folder)) {
    message("Extracting ZIP file...")
    unzip(zip_file, exdir = dest_dir)
  } else {
    message("Data already extracted. Skipping extraction.")
  }
  
  message("Download and extraction complete.")
}
